---
title: "Relatório de análise da Assessoria"
date: '`r paste("Porto Alegre, ", paste(format(Sys.Date(), "%d"),format(Sys.Date(), "%B"), format(Sys.Date(), "%Y"), sep = " de "), sep = "")`'
output:
  bookdown::word_document2:
      reference_docx: plan_analise.docx
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#install.packages('formatR')
#library(formatR)
```

***

# Apresentação

Este documento tem como objetivo apresentar os métodos estatísticos para análise de dados do trabalho de doutorado __"Spatiotemporal patterns of carrion biomass of marine tetrapods in the interface ocean-land in the southern Brazilian coastline"__ do assessorado __Maurício Tavares__ do __Programa de Pós-Graduação em Biologia Animal__ do __Instituto de Biociências__ da __Universidade Federal do Rio Grande do Sul__. 


A seguir são apresentados os objetivos do trabalho de doutorado, as variáveis do estudo e análise estatística. 

## Equipe

__Professor:__ Rodrigo Citton Padilha dos Reis

__Alunos:__

- Celso Menoti da Silva
- Enzo Bertoldi Oestreich
- Nicolas Mathias Hahn
- Victor Frank Gomes

\newpage

# Introdução

## Objetivos

### Objetivo geral

Fornecer uma quantificação robusta e abrangente da biomassa de carcaças no importante e ainda pouco estudado ecossistema: a interface oceano-terra.

### Objetivos específicos

- Descrever a distribuição espaço-temporal da biomassa de carcaças de animais marinhos encalhados na costa litorânea brasileira.
- Estimar a quantidade de biomassa das carcaças dos animais marinhos encalhados (separada por espécie e multiplicada pela abundância de cada uma).

# Análise estatística

A análise estatísica empregada no artigo _"Spatiotemporal patterns of carrion biomass of marine tetrapods in the interface ocean-land in the southern Brazilian coastline"_ responde aos objetivos do mesmo.

## Sugestões de análise

- Verificação do código da análise estatística;
- Reanálise a partir do código da análise estatística;
- __Análise de dados circulares:__ descrição dos dados anuais de abundância e riqueza de espécies, pode ser realizado teste de distribuição uniforme ao longo do ano (contra a alternativa de agrupamentos em torno de alguns períodos específicos no tempo).
    + Teste de Rayleigh e $U^2$ de Watson;
    + Pacote em `R` `circular`
- Estimativa do erro padrão relativo.
